name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile src/__main__.py
    - uses: actions/upload-artifact@v2
      with:
        name: project-manager
        path: dist/__main__
        if-no-files-found: error
